### ISSUE TITLE
Does this repo support GFX 1102 and 1101 on Linux(Ubuntu)?

### ISSUE THREAD

**Issue by Looong01** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#10]
I want to buy a laptop, Asus TUF gaming A16 with GPU AMD 7700S or 7600S. These are GFX 1102 and 1103.
Does this repo support GFX 1102 and 1101 on Linux(Ubuntu)?

**Comment by likelovewant** [comment]
gfx1100, gfx1101 and gfx1102 is officially supported by AMD ROCm ,you don't need do anything . simply install ROCms  will get support.
@Looong01

**Comment by likelovewant** [comment]
it's seems ROCms didn't compile the gfx1101 and gfx1102 in [linux latest release]( https://rocmdocs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html). However ,it's official support in [windows](https://rocm.docs.amd.com/projects/install-on-windows/en/develop/reference/system-requirements.html) .
it's actually easier to use . simply set  ` export HSA_OVERRIDE_GFX_VERSION=11.0.0` can override your system's default and provide support for gfx1101,1102,110x.... and similar GPUs. which is better so far , as gfx1100 has more function support ,such as MIOPEN ( CUDA CUDNN) . Otherwise , you may build the rocblas from source as example in the [wiki]( https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/wiki) for windows or [ linux ](https://rocm.docs.amd.com/projects/rocBLAS/en/latest/install/Linux_Install_Guide.html), and you may not edit anything as the example show in this repo's wiki , the official has all the data available in the github. it's much more easier .

**Comment by Looong01** [comment]
Thank u so much for the reply!
And the last question: Is building rocblas from source the only last option for me to run PyTorch/MIOpen in WSL? Cuz ```export HSA_OVERRIDE_GFX_VERSION=11.0.0``` is useless(I try it on 6700XT)
![image](https://github.com/user-attachments/assets/ac06f335-dd6f-459f-a32e-bb43900fa615)

**Comment by likelovewant** [comment]
it's useless in 6700XT currenctly due to the rocm wsl limited supported . However , there are some unofficial modified drivers can enable this function and make it support in wsl . you may also build MIOPEN from source by some tricks shows in the wiki of this repo. ( by edit the logic file (.yaml file）to get your card support.
