### ISSUE TITLE
Could not initialize Tensile library

### ISSUE THREAD

**Issue by SantaSpeen** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#12]
rocBLAS error: Could not load C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary_lazy_gfx1103.dat

rocBLAS error: Could not initialize Tensile library
Для продолжения нажмите любую клавишу . . .

**Comment by likelovewant** [comment]
Not sure what are your using for ? SD or Ollama or others.
1, make sure your also has rocbals.dll replaced the original one . otherwise ,it will show this error 
2, make sure you rocblas library match your HIPSDK (ROCM) Version.5.7 or 6.1.2 , mismatch will cause error .
3, make sure has latest drivers.
@SantaSpeen

**Comment by SantaSpeen** [comment]
1. Yep `set COMMANDLINE_ARGS=--use-zluda --medvram`
2. 6.1.2
3. latest

**Comment by SantaSpeen** [comment]
And I have same error on linux

**Comment by SantaSpeen** [comment]
![image](https://github.com/user-attachments/assets/145d3324-69e6-4b81-b55a-0dbf65863f3b)
![image](https://github.com/user-attachments/assets/166a7f1e-a16c-4b0f-b8f4-3efd70a12a09)
![image](https://github.com/user-attachments/assets/c3ea6655-6750-41b5-b726-0fc31347eb65)

**Comment by SantaSpeen** [comment]
my bad
all is fine
