### ISSUE TITLE
6.1 Libs don't recognise AMD RX580 2048SP

### ISSUE THREAD

**Issue by aluisperezh** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#14]
With 5.7 libs my RX580 card is found and works as "gfx803", but not with 6.1 libs, in any version I tried. 

Maybe there is a difference between "standard" RX580 and mine that wasn't checked in 5.7 but it is in 6.1. The card device code is "1002 6**7**DF" while for my card this device code is "1002 6**F**DF".

I've tried to check source code, but I cannot find it anywhere. Files identified as source code do not contain it (or at least I can't find it).

Regards.

**Comment by likelovewant** [comment]
The device code can be found in [rocblas logic file](https://github.com/ROCm/rocBLAS/blob/develop/library/src/blas3/Tensile/Logic/asm_full/r9nano/r9nano_Cijk_Ailk_Bjlk_DB.yaml),ie , [Device 7300], also can be `67DF` or `6FDF` ,Even if found, these codes
might not be recognized due to significant code changes in ROCm versions above 6.0. These changes removed core
functionalities for old cards from the source code beyond just rocBLAS.

 doubt it's **highly probable** that the issue stems from driver inconsistencies.

**Comment by likelovewant** [comment]
Also you may test [koboldcpp-rocm](https://github.com/YellowRoseCx/koboldcpp-rocm) 
 https://github.com/YellowRoseCx/koboldcpp-rocm/releases/tag/deps-v6.2.0

**Comment by likelovewant** [comment]
There is no others method to make it support  currently .close this for now . feel free to reopen it or open a new  if you still have any other question.

**Comment by likelovewant** [comment]
There is no others method to make it support currently .close this for now . feel free to reopen it or open a new if you still have any other question.

**Comment by likelovewant** [comment]
1

**Comment by likelovewant** [comment]
There is no others method to make it support currently .close this for now . feel free to reopen it or open a new if you still have any other question.
